### ISSUE TITLE
mcollective issue

### ISSUE THREAD

**Issue by nik786** [example42/puppet-mcollective#31]
I have configured mcollective with activemq and puppet on ubuntu machine

cat /etc/hosts
192.168.10.25 puppetmaster
192.168.10.26 puppetclinet

puppetmaster

apt-get install puppet-common puppetmaster
apt-get install mcollective-package-agent mcollective-service-agent mcollective-puppet-agent

cat /etc/puppet/puppet.conf

cat /etc/activemq/credential.properties
activemq.username=system
activemq.password=manager

cat /etc/mcollective/client.cfg

collectives = mcollective
connector = activemq
direct_addressing=1
libdir = /usr/share/mcollective/plugins
logger_type = console
loglevel = warn
main_collective = mcollective
daemonize = 1
classesfile = /var/lib/puppet/state/classes.txt

plugin.activemq.pool.1.host = puppetmaster
plugin.activemq.pool.1.password = manager
plugin.activemq.pool.1.port = 61613
plugin.activemq.pool.1.user = system
plugin.activemq.pool.size = 1
plugin.activemq.randomize = true
# Plugins
securityprovider = psk
plugin.psk = acb786123456

# Facts
factsource = yaml
plugin.yaml = /etc/mcollective/facts.yaml

service mocollective restart
service activemq restart

but when try to ping

mco ping 

Im receiving following error

/usr/lib/ruby/vendor_ruby/systemu.rb:31: warning: Insecure world writable dir /home/vagrant in PATH, mode 040777
error 2017/12/25 16:54:49: client.rb:39:in `rescue in initialize' Timeout occured while trying to connect to middleware

The ping application failed to run: execution expired

execution expired (MCollective::ClientTimeoutError)
        from /usr/lib/ruby/vendor_ruby/connection/utils.rb:142:in `sleep'  <----
        from /usr/lib/ruby/vendor_ruby/connection/utils.rb:142:in `rescue in block in socket'
        from /usr/lib/ruby/vendor_ruby/connection/utils.rb:115:in `block in socket'
        from <internal:prelude>:10:in `synchronize'
        from /usr/lib/ruby/vendor_ruby/connection/utils.rb:109:in `socket'
        from /usr/lib/ruby/vendor_ruby/stomp/connection.rb:143:in `initialize'
        from /usr/lib/ruby/vendor_ruby/mcollective/connector/activemq.rb:296:in `new'
        from /usr/lib/ruby/vendor_ruby/mcollective/connector/activemq.rb:296:in `connect'
        from /usr/lib/ruby/vendor_ruby/mcollective/client.rb:36:in `block in initialize'
        from /usr/lib/ruby/vendor_ruby/mcollective/client.rb:35:in `initialize'
        from /usr/lib/ruby/vendor_ruby/mcollective/application/ping.rb:52:in `new'
        from /usr/lib/ruby/vendor_ruby/mcollective/application/ping.rb:52:in `main'
        from /usr/lib/ruby/vendor_ruby/mcollective/application.rb:293:in `run'
        from /usr/lib/ruby/vendor_ruby/mcollective/applications.rb:23:in `run'
        from /usr/bin/mco:33:in `<main>'

puppetclinet
cat /etc/hosts
192.168.10.25 puppetmaster
192.168.10.26 puppetclinet

apt-get install puppet
apt-get install mcollective ruby-stomp mcollective-client
apt-get install mcollective-package-client mcollective-service-client mcollective-puppet-client

cat /etc/mcollective/client.cfg
client.cfg content i have copied in server.cfg

service mocollective restart
service activemq restart

can you tell me how to resolve this one?

**Comment by alvagante** [comment]
You should check if activemq service is actully running and reachable from the client, and if credentials are correct. Its logs might give some more hints.
Note anyway that this mcollective module is very old and not maintained anymore.
I suggest you to use Choria to configure mcollective.

**Comment by nik786** [comment]
activemq is running.let me try choria.logs are not providing much discrepancy details.
